"""Newer Tables Added

Revision ID: 90c7f3be7edd
Revises: 
Create Date: 2026-04-06 12:38:35.980599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c7f3be7edd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_Table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_password', sa.String(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=True),
    sa.Column('user_role', sa.Enum('USER', 'ADMIN', 'RESTAURANT_OWNER', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_index(op.f('ix_User_Table_user_id'), 'User_Table', ['user_id'], unique=False)
    op.create_table('Restaurent_Table',
    sa.Column('Restaurent_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('Restaurent_name', sa.String(), nullable=False),
    sa.Column('Restaurent_address', sa.String(), nullable=False),
    sa.Column('Restaurent_phone', sa.Integer(), nullable=False),
    sa.Column('Restaurent_rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['User_Table.user_id'], ),
    sa.PrimaryKeyConstraint('Restaurent_id')
    )
    op.create_index(op.f('ix_Restaurent_Table_Restaurent_id'), 'Restaurent_Table', ['Restaurent_id'], unique=False)
    op.create_index(op.f('ix_Restaurent_Table_Restaurent_rating'), 'Restaurent_Table', ['Restaurent_rating'], unique=False)
    op.create_index(op.f('ix_Restaurent_Table_owner_id'), 'Restaurent_Table', ['owner_id'], unique=False)
    op.create_table('Menu_Table',
    sa.Column('cuisine_id', sa.Integer(), nullable=False),
    sa.Column('cuisine_name', sa.String(), nullable=False),
    sa.Column('restaurent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurent_id'], ['Restaurent_Table.Restaurent_id'], ),
    sa.PrimaryKeyConstraint('cuisine_id')
    )
    op.create_index(op.f('ix_Menu_Table_restaurent_id'), 'Menu_Table', ['restaurent_id'], unique=False)
    op.create_table('Orders_Table',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('restaurent_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurent_id'], ['Restaurent_Table.Restaurent_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User_Table.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_Orders_Table_order_id'), 'Orders_Table', ['order_id'], unique=False)
    op.create_index(op.f('ix_Orders_Table_restaurent_id'), 'Orders_Table', ['restaurent_id'], unique=False)
    op.create_index(op.f('ix_Orders_Table_total_amount'), 'Orders_Table', ['total_amount'], unique=False)
    op.create_table('Items_Table',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.Column('item_rating', sa.Integer(), nullable=False),
    sa.Column('item_availability', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['Menu_Table.cuisine_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_Items_Table_item_id'), 'Items_Table', ['item_id'], unique=False)
    op.create_index(op.f('ix_Items_Table_menu_id'), 'Items_Table', ['menu_id'], unique=False)
    op.create_table('OrderItems_Table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['Items_Table.item_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['Orders_Table.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_OrderItems_Table_id'), 'OrderItems_Table', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_OrderItems_Table_id'), table_name='OrderItems_Table')
    op.drop_table('OrderItems_Table')
    op.drop_index(op.f('ix_Items_Table_menu_id'), table_name='Items_Table')
    op.drop_index(op.f('ix_Items_Table_item_id'), table_name='Items_Table')
    op.drop_table('Items_Table')
    op.drop_index(op.f('ix_Orders_Table_total_amount'), table_name='Orders_Table')
    op.drop_index(op.f('ix_Orders_Table_restaurent_id'), table_name='Orders_Table')
    op.drop_index(op.f('ix_Orders_Table_order_id'), table_name='Orders_Table')
    op.drop_table('Orders_Table')
    op.drop_index(op.f('ix_Menu_Table_restaurent_id'), table_name='Menu_Table')
    op.drop_table('Menu_Table')
    op.drop_index(op.f('ix_Restaurent_Table_owner_id'), table_name='Restaurent_Table')
    op.drop_index(op.f('ix_Restaurent_Table_Restaurent_rating'), table_name='Restaurent_Table')
    op.drop_index(op.f('ix_Restaurent_Table_Restaurent_id'), table_name='Restaurent_Table')
    op.drop_table('Restaurent_Table')
    op.drop_index(op.f('ix_User_Table_user_id'), table_name='User_Table')
    op.drop_table('User_Table')
    # ### end Alembic commands ###
